---
    - name: add group nginx
      group: name=nginx state=present
    - name: add user nginx
      user: name=nginx group=nginx home=/usr/share/nginx createhome=no
    - name: download nginx
    # module unarchive has bug
      get_url: url=https://nginx.org/download/nginx-{{nginx_version}}.tar.gz dest=/opt/nginx-{{nginx_version}}.tar.gz
    - name: extract archive
      command: /bin/tar xvf /opt/nginx-{{nginx_version}}.tar.gz -C /opt/ creates=/opt/nginx-{{nginx_version}}
    - name: install dependencies for nginx
      apt: pkg=nginx state=build-dep
    - name: install nginx - configure
      command: chdir=/opt/nginx-{{nginx_version}}/ ./configure --prefix=/usr/share/nginx --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_stub_status_module --with-threads --with-stream --with-stream_ssl_module creates=/usr/share/nginx
    - name: install nginx - make
      command: chdir=/opt/nginx-{{nginx_version}}/ make creates=/usr/share/nginx
    - name: install nginx - make install
      command: chdir=/opt/nginx-{{nginx_version}}/ make install creates=/usr/share/nginx
    - name: change ownership of nginx installation
      file: path=/usr/share/nginx/ owner=nginx group=nginx state=directory recurse=yes
